config/routes.rb
Rails.application.routes.draw do
  resource :write_database do
    get :switch
    post :switch
  end
  resource :view_beacons
end

app/models/packet.rb
class Packet < ActiveRecord::Base
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |model|
        csv << model.attributes.values_at(*column_names)
      end
    end
  end
end

app/models/switch.rb
class Switch < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/view_beacons_controller.rb
require 'csv'

class ViewBeaconsController < ApplicationController
  def show
    if params[:format].blank?
      @switch = Switch.where(on: 1)
      pp params
    else
      a={}
      on = Switch.find_by_id(params[:format])
      @packets = Packet.where(["created_at >= ? and created_at <= ?", on.created_at, on.created_at+30])

      # synapsensorごとのパケット内訳
      @packets.each do |e|
        a[e.advdata.split(":").last]=0 unless a.has_key?(e.advdata.split(":").last)
        a[e.advdata.split(":").last]+=1
      end
      pp a
      #return render text: get_csv_str(@packets)
      #csv出力
      return render csv: @packets
    end
  end

  def get_csv_str( packets )
      result = "\"id\",\"bdaddress\",\"deviceaddress\",\"rssi\",\"created_at\"\n"
      packets.each do |e|
        result += "#{e.id},\"#{e.bdaddress}\",\"#{e.advdata}\",#{e.rssi},\"#{e.created_at}\"\n"
      end
      result
  end
end

app/controllers/write_databases_controller.rb
class WriteDatabasesController < ApplicationController

  skip_before_filter :verify_authenticity_token, only: [:create]
  def create
    if @switch = Switch.last
      @switch.on == 1 ? on = true : on = false
    end
    if on
      packet = Packet.create do |s|
        s.sequence_no = params["SequenceNo"]
        s.bdaddress = params["BdAddress"]
        s.advdata = params["DeviceAddress"]
        s.created_at = params["DateTime"]
        s.rssi = params["Rssi"]
      end
    end
    render :text => "OK", :status => 200
  end

  def switch
    @packet = Packet.last
    if @switch = Switch.last
      @switch.on == 1 ? on = true : on = false
    end
    if params[:switch].present?
      @switch = Switch.create do |s|
        if @switch.present?
          s.on = @switch.on == 1 ? 0 : 1
        else
          s.on = 1
        end
          s.label = params[:label]
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AdvertisePacketStatistics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/view_beacons/show.html.erb
<% if @switch.present? %>
  <% @switch.each do |e| %>
    <%= link_to e.label, view_beacons_path(e.id) if e.label.present? %>
    <% if e.label.present? %>
      <% @count = 0 %>
      <% @lost = 0 %>
      <% @seq_no = 0 %>
      ,<% Packet.where(["created_at >= ? and created_at <= ?", e.created_at, e.created_at+30]).each do |p| %>
         <% @count+=1 %>
         <% @lost +=1 if @seq_no+1 != p.sequence_no %>
         <% @seq_no = p.sequence_no %>
      <% end %>
      <%= @count %>, ロスト:<%if 1 >= @lost %>
        <%= 0 %>
      <% else %>
        <font style="color:red;">
          <%= @lost-1 %>
        </font>
      <% end %><br />
    <% end %>
  <% end %>
<% else %>
  <%= '"id","bdaddress","advdata","rssi","created_at"' %><br />
  <% @packets.each do |e| %>
    <%= e.id %>,"<%= e.bdaddress %>","<%= e.advdata %>",<%= e.rssi %>,"<%= e.created_at %>"<br />
  <% end %>
<% end %>

app/views/write_databases/switch.html.erb
<meta name="viewport" content="width=device-width, initial-scale=2.0, maximum-scale=1.3, user-scalable=0;">
<% if @switch.present? %>
  Status: <%= 1 == @switch.on ? "on" : "off" %>
  Label: <%= @switch.label %>
<% end %>

<%= form_tag('/write_database/switch', method: :post) do %>
  <%= hidden_field_tag "switch", value: 1 %>
  <%= text_field_tag "label" %>
  <%= submit_tag "ON/OFF"  %>
<% end %>

<% if @packet.present? %>
  <%= @packet.created_at.strftime("%Y-%m-%d %H:%M:%S") %>
<% end %>
<%= button_to "更新", action: :switch %>